
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hunger-2-helm
spec:
 scaleTargetRef:
   apiVersion: apps/v1beta1
   kind: Deployment
   name: hunger-2-helm
 minReplicas: 3
 maxReplicas: 5
 targetCPUUtilizationPercentage: 85
